# Environment URL's
baseUrlWeb=https://itigraduation.pythonanywhere.com
homeUrl=/
loginUrl=/web/login
registerUrl=/web/register
orderUrl=/web/orders
productsUrl=/web/products
cartUrl=/web/cart
helpUrl=/web/help
contactUrl=/web/contact
advanceSearchUrl=/web/advanced-search
profileUrl=/web/profile
notificationsUrl=/web/notifications
wishlistUrl=/web/wishlist